### ISSUE TITLE
Recall scene not working

### ISSUE THREAD

**Issue by stijnve** [bitfocus/companion-module-allenheath-ahm#2]
Hi,

Recall scene is working fine on the AHM64, but not with the newly AHM32 or 16.
Although other functions like mute do work.

Br, Stijn

**Comment by rohanwright** [comment]
Brand new AHM64 won't work with scene recall, not sure if somethings changed with a new revision or firmware for AHM or if it's related to Companion 3?

**Comment by bryce-seifert** [comment]
Is Scene recall still an issue? Testing on AHM64 v1.41 I was not able to recreate the failure.

If It is, are there any errors in the logs?

**Comment by bryce-seifert** [comment]
@rohanwright @stijnve Is this still an issue?
