### ISSUE TITLE
How to update to 2.0

### ISSUE THREAD

**Issue by sethmwiese** [bitfocus/companion-module-allenheath-ahm#4]
This is a 2 part question and it is a total novice question, so please, some grace.

In Companion 2.4.2 this AHM module is only showing up as 1.0.2. I have been unable figure out how to update to 1.0.3. if my understanding is correct the 2.0 module is for Companion 3.0.

That being said, I updated Companion to 3.0 and there is no module for AHM available.

Part one : Is there a way to update/import modules that I am just missing with Companion?

Part two : Does the update (1.0.3 or 2.0) have presets recall? Because if not, That is what I am trying to do so it will be useless in for my current needs, so is there anyone that can program this feature?

Thank you!
- Seth

**Comment by bryce-seifert** [comment]
> Part one : Is there a way to update/import modules that I am just missing with Companion?

There is no current way to update modules on a per module basis, you should update the Companion app is as a whole to access v2.0 of the module

> Part two : Does the update (1.0.3 or 2.0) have presets recall? Because if not, That is what I am trying to do so it will be useless in for my current needs, so is there anyone that can program this feature?

Both 1.0.3 and 2.0 have preset recall. The action title is currently "Recall a scene"
