### ISSUE TITLE
Error on action in AHM

### ISSUE THREAD

**Issue by ryProton** [bitfocus/companion-module-allenheath-ahm#5]
Getting an error in log on mute action:
Instance/Wrapper/AHM: Error executing action: Cannot access 's' before initialization

Shows connected to AHM in Connections. Created a button and a trigger but neither work, just get this error in logs.

Thanks for your time!

**Comment by bryce-seifert** [comment]
Which version of Companion are you using?
Also which mute action (mute input, mute zone, Mute input to zone)?

**Comment by ryProton** [comment]
3.2.1 
Mute input to zone

**Comment by bryce-seifert** [comment]
@ryProton This should be fixed in the latest beta of Companion

**Comment by ryProton** [comment]
That works, thank you!
