### ISSUE TITLE
Additions to the AHM module

### ISSUE THREAD

**Issue by ben-burnett** [bitfocus/companion-module-allenheath-ahm#7]
I would love to be able to use the Source selector within a zone. In addition if the "Input to Zone Send Level" command could be added to that'd be amazing.

These can be achieved using the Midi commands over TCP listed in the AHM Protocol v1.4 document.

My particular use case is that currently, in a no longer supported control system, when a button is pushed the AHM changes the source selector and adjusts the levels of the inputs on the zone input mixer. (Both channels remain unmuted, but levels shift dependent on which source is selected)

With the 4 current commands in the AHM module this is impossible to achieve. I have used Packet Sender to test the Midi over TCP commands and I have achieved the right response from the AHM, but using the same Midi HEX command via the generic TCP module in Companion doesn't work.

Attached is the Protocol document.

Any help is GREATLY appreciated. Thanks so much!

[AHM-TCP-Protocol-V1.4.pdf](https://github.com/bitfocus/companion-module-allenheath-ahm/files/14546535/AHM-TCP-Protocol-V1.4.pdf)

**Comment by bryce-seifert** [comment]
Just updating, I've done some work and have Source selector working. Just a little more testing to do before I merge it.

One question regarding the "Input to Zone Send Level" action. Are you wanting this to be dynamic based on the selected source, or do you simply want to select both a zone and input?

**Comment by ben-burnett** [comment]
Mate - thank you so much!

Great question - if I'm understanding correctly, are you asking if the level should auto change dependant on which source has been selected? So for example if I select FOH, it takes the FOH input and the send level goes up to 0db? And if I then select a Broadcast input it then takes that input to 0db and pulling everything else down?

if so - this is the end goal, but could be limiting for other users potentially? Could it be a tick box within the Source Selector option? So if this is selected, then do this action? But then also have a separate action in the module to do it on it's own? I think that's what you're offering in the second option.

I could be making no sense! Apologies. Hope that is helpful?

Huge thanks Bryce!! Happy Easter!

**Comment by ben-burnett** [comment]
Hey @bryce-seifert - hope you're well mate? Curious to know if you'd made any progress on this? Very much appreciate your kindness and time looking into this for me. Zero pressure :)

**Comment by bryce-seifert** [comment]
@ben-burnett Sorry for the delay, I got this partially done and then got really busy. I'll try to remember where I left off and get back to this soon, thanks for your patience

**Comment by rtdean** [comment]
[AHM TCP Protocol v1.5](https://www.allen-heath.com/content/uploads/2024/10/AHM-TCP-Protocol-V1.5.pdf) is now available.

In re the swapping of audio levels to -Inf vs 0/Unity, the AHM device itself can do this if you are using the Input Selectors with the XPoint Routing.  So it might be that by implementing that you replicate what the previous device was doing (especially if the previous device was running Custom Control or something...)

**Comment by bryce-seifert** [comment]
Thanks to  https://github.com/bitfocus/companion-module-allenheath-ahm/pull/20 Input to Zone Send Level actions should now be possible.
