### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by tvcontrol** [bitfocus/companion-module-allenheath-ahm#9]
Is there a plan to add volume control? Input, Zone, and crosspoint control?

https://www.allen-heath.com/content/uploads/2023/11/AHM-TCP-Protocol-V1.4.pdf

**Comment by bryce-seifert** [comment]
Level control has now been added (https://github.com/bitfocus/companion-module-allenheath-ahm/pull/20), and will be available in Companion betas by tomorrow
